/*
 * Copyright (C) 2025 the Jasper Server OS Authors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2005-2023. Cloud Software Group, Inc. All Rights Reserved.
 * http://www.jaspersoft.com.
 *
 * Unless you have purchased a commercial license agreement from Jaspersoft,
 * the following license terms apply:
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.jaspersoft.jasperserver.test;

import com.jaspersoft.jasperserver.api.common.domain.ExecutionContext;
import com.jaspersoft.jasperserver.api.common.util.StaticExecutionContextProvider;
import com.jaspersoft.jasperserver.api.metadata.common.domain.*;
import com.jaspersoft.jasperserver.api.metadata.common.domain.client.FolderImpl;
import com.jaspersoft.jasperserver.api.metadata.jasperreports.domain.JdbcReportDataSource;
import com.jaspersoft.jasperserver.api.metadata.jasperreports.domain.JndiJdbcReportDataSource;
import com.jaspersoft.jasperserver.api.metadata.jasperreports.domain.ReportUnit;
import com.jaspersoft.jasperserver.api.metadata.jasperreports.domain.VirtualReportDataSource;
import com.jaspersoft.jasperserver.api.metadata.security.JasperServerPermission;
import com.jaspersoft.jasperserver.api.metadata.user.domain.Role;
import com.jaspersoft.jasperserver.api.metadata.user.domain.User;
import com.jaspersoft.jasperserver.api.metadata.xml.domain.impl.ResourceDescriptor;
import com.jaspersoft.jasperserver.crypto.EncryptionEngine;
import com.jaspersoft.jasperserver.crypto.KeystoreManager;
import static com.jaspersoft.jasperserver.crypto.conf.Defaults.BuildEnc;
import com.jaspersoft.jasperserver.util.test.BaseServiceSetupTestNG;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.io.InputStream;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * @author srosen
 *
 * Creates the full production data for CE using the TestNG framework
 *
 * 2013-08-14: tkavanagh
 *   Removed sample report unit resources that were found in the /reports/samples folder. These
 *   used to be sample reports given the customers as standard samples. But these are now
 *   replaced with nicer reports in /public/samples as of the 5.5 release. The samples are now
 *   considered test resources for integration-tests. The are created and deleted in a different
 *   file. 
 */
public class FullDataCreateTestNG extends BaseServiceSetupTestNG {

    protected final Log m_logger = LogFactory.getLog(FullDataCreateTestNG.class);

    @BeforeClass()
	protected void onSetUp() throws Exception {
		m_logger.info("onSetUp() called");
	}

    @AfterClass()
	public void onTearDown() {
		m_logger.info("onTearDown() called");
	}

    /*
    * This method is the starting point for adding resources that comprise the Full production
    * data for the Community Edition (CE) product.
    *   Full Data == Sample Data
    */
    @Test()
	public void createFullDataResources() throws Exception {
        m_logger.info("createFullDataResources() called");

        addHibernateRepositoryDataSourceResources();
        addHibernateRepositoryReportResources();
        addContentRepositoryTestResources();
        addUserAuthorityServiceTestResources();
        addAnalysisResources();
        addInteractiveReportResources();
        
        addDefaultDomainWhitelist();
        addDBProfileAttributes();
    }


    private void addUserAuthorityServiceTestResources() {
        m_logger.info("addUserAuthorityServiceTestResources() called");

        User newUser = createUser(BaseServiceSetupTestNG.USER_JOEUSER, BaseServiceSetupTestNG.USER_JOEUSER, BaseServiceSetupTestNG.USER_JOEUSER_FULLNAME);
        addRole(newUser, BaseServiceSetupTestNG.ROLE_USER);
    }

    private void addContentRepositoryTestResources() {
        m_logger.info("addContentRepositoryTestResources() called");

        m_logger.info("addContentRepositoryTestResources() => creating /ContentFiles");
        Folder dsFolder = new FolderImpl();
        dsFolder.setName("ContentFiles");
        dsFolder.setLabel("Content Files");
        dsFolder.setDescription("Content files generated by reports");
        getUnsecureRepositoryService().saveFolder(null, dsFolder);

        m_logger.info("addContentRepositoryTestResources() => creating /ContentFiles/html");
        Folder newFolder = new FolderImpl();
        newFolder.setParentFolder(dsFolder);
        newFolder.setName("html");
        newFolder.setLabel("html");
        getUnsecureRepositoryService().saveFolder(null, newFolder);

        m_logger.info("addContentRepositoryTestResources() => creating /ContentFiles/pdf");
        newFolder = new FolderImpl();
        newFolder.setParentFolder(dsFolder);
        newFolder.setName("pdf");
        newFolder.setLabel("pdf");
        getUnsecureRepositoryService().saveFolder(null, newFolder);

        m_logger.info("addContentRepositoryTestResources() => creating /ContentFiles/xls");
        newFolder = new FolderImpl();
        newFolder.setParentFolder(dsFolder);
        newFolder.setName("xls");
        newFolder.setLabel("xls");
        getUnsecureRepositoryService().saveFolder(null, newFolder);
    }

    private void addHibernateRepositoryDataSourceResources()  {
        m_logger.info("addHibernateRepositoryDataSourceResources() called");

        // create the main datasources folder
        // create the JndiDS, the RepoDS, the JdbcDS, the BeanDS, and the TableModelDS
        m_logger.info("addHibernateRepositoryDataSourceResources() => creating /datasources");
        Folder dsFolder = new FolderImpl();
        dsFolder.setName("datasources");
        dsFolder.setLabel("Data Sources");
        dsFolder.setDescription("Data Sources used by reports");
        getUnsecureRepositoryService().saveFolder(null, dsFolder);

        createJndiDS();
        createRepoDS();
        createJdbcDS();
    }

    private void addHibernateRepositoryReportResources()  {
        m_logger.info("addHibernateRepositoryReportResources() called");

        // create an images folder and sample image
        createImagesFolderAndSampleImage();

        // 2013-08-14: removed creation of /reports/samples reports in this file 

        // create the main analysis folder
        m_logger.info("addHibernateRepositoryReportResources() => adding /analysis");
        Folder analysisFolder = new FolderImpl();
        analysisFolder.setName("analysis");
        analysisFolder.setLabel("Analysis Components");
        analysisFolder.setDescription("Analysis Components");
        getUnsecureRepositoryService().saveFolder(null, analysisFolder);

        // create the analysis/datasources folder
        m_logger.info("addHibernateRepositoryReportResources() => adding /analysis/datasources");
        Folder analysisDsFolder = new FolderImpl();
        analysisDsFolder.setName("datasources");
        analysisDsFolder.setLabel("Analysis Data Sources");
        analysisDsFolder.setDescription("Data sources used by Analysis");
        analysisDsFolder.setParentFolder(analysisFolder);
        getUnsecureRepositoryService().saveFolder(null, analysisDsFolder);

        // setup the execute only permissions
        setupExecuteOnlyPermissions();

        // setup the no access permissions
        setupNoAccessPermissions();
    }

    private void setupExecuteOnlyPermissions() {
        Role userRole = getRole(ROLE_USER);
        createObjectPermission("/datasources", userRole, JasperServerPermission.EXECUTE.getMask());

        // bug 21880; we still need read access for datatypes
        // createObjectPermission("/datatypes", userRole, JasperServerPermission.EXECUTE);
        createObjectPermission("/images", userRole, JasperServerPermission.EXECUTE.getMask());
        createObjectPermission("/themes", userRole, JasperServerPermission.EXECUTE.getMask());
    }

    private void setupNoAccessPermissions() {
        // bug 29635; we need prevent access for User role, so only
        // ROLE_SUPERUSER & ROLE_ADMINISTRATOR should be able to execute that data source.
        Role userRole = getRole(ROLE_USER);
        createObjectPermission("/datasources/repositoryDS", userRole, JasperServerPermission.NOTHING.getMask());
    }

    private void createImagesFolderAndSampleImage() {
        m_logger.info("createImagesFolderAndSampleImage() => creating /images");
        Folder folder = new FolderImpl();
        folder.setName("images");
        folder.setLabel("Images");
        folder.setDescription("Folder containing reusable images");
        getUnsecureRepositoryService().saveFolder(null, folder);

        m_logger.info("createImagesFolderAndSampleImage() => creating /images/JRLogo");
        FileResource image = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        image.setFileType(FileResource.TYPE_IMAGE);
        image.readData(getClass().getResourceAsStream("/images/jasperreports.png"));
        image.setName("JRLogo");
        image.setLabel("JR logo");
        image.setDescription("JR logo");
        image.setParentFolder(folder);

        getUnsecureRepositoryService().saveResource(null, image);
    }

    private void createJndiDS() {
        JndiJdbcReportDataSource datasource = (JndiJdbcReportDataSource) getUnsecureRepositoryService().newResource(null, JndiJdbcReportDataSource.class);
        datasource.setName("JServerJNDIDS");
        datasource.setLabel("JServer JNDI Data Source");
        datasource.setDescription("JServer JNDI Data Source");
        datasource.setJndiName(getJdbcProps().getProperty("test.jndi"));
        datasource.setParentFolder("/datasources");

        getUnsecureRepositoryService().saveResource(null, datasource);
    }

    private void createRepoDS() {
        JndiJdbcReportDataSource datasource = (JndiJdbcReportDataSource) getUnsecureRepositoryService().newResource(null, JndiJdbcReportDataSource.class);
        datasource.setName("repositoryDS");
        datasource.setLabel("Jasperserver Repository SQL data source");
        datasource.setDescription("Jasperserver Repository SQL data source for reporting");
        datasource.setJndiName(getJdbcProps().getProperty("metadata.jndi"));
        datasource.setParentFolder("/datasources");

        getUnsecureRepositoryService().saveResource(null, datasource);
    }

    private void createJdbcDS() {
        JdbcReportDataSource datasource = (JdbcReportDataSource) getUnsecureRepositoryService().newResource(null, JdbcReportDataSource.class);
        datasource.setName("JServerJdbcDS");
        datasource.setLabel("JServer Jdbc Data Source");
        datasource.setDescription("JServer Jdbc Data Source");
        datasource.setParentFolder("/datasources");

        datasource.setDriverClass(getJdbcProps().getProperty("test.jdbc.driverClassName"));
        datasource.setConnectionUrl(getJdbcProps().getProperty("test.jdbc.url"));
        datasource.setUsername(getJdbcProps().getProperty("test.jdbc.username"));

		String passwd = getJdbcProps().getProperty("test.jdbc.password");
		if (EncryptionEngine.isEncrypted(passwd)) {
			KeystoreManager ksManager = KeystoreManager.getInstance();
			passwd = EncryptionEngine.decrypt(ksManager.getKeystore(null).getKey(BuildEnc.getConfId()), passwd);
		}
		datasource.setPassword(passwd);

        getUnsecureRepositoryService().saveResource(null, datasource);
    }

    private void setCommon(Resource res, String id) {
        res.setName(id);
        res.setLabel(id + " Label");
        res.setDescription(id + " description");
    }

    protected void createFoodmartJDBCDataSourceResource() throws Exception {
        m_logger.info("createFoodmartJDBCDataSourceResource() => creating /analysis/datasources/FoodmartDataSource");

		String passwd = getJdbcProps().getProperty("foodmart.jdbc.password");
		if (EncryptionEngine.isEncrypted(passwd)) {
			KeystoreManager ksManager = KeystoreManager.getInstance();
			passwd = EncryptionEngine.decrypt(ksManager.getKeystore(null).getKey(BuildEnc.getConfId()), passwd);
		}
		createJDBCDataSourceResource("/analysis/datasources",
                        "FoodmartDataSource",
                        "Foodmart Data Source",
                        "Foodmart Data Source",
                        getJdbcProps().getProperty("foodmart.jdbc.driverClassName"),
                        getJdbcProps().getProperty("foodmart.jdbc.url"),
                        getJdbcProps().getProperty("foodmart.jdbc.username"),
                        passwd);
    }

    protected void createFoodmartJNDIDataSourceResource() {
        m_logger.info("createFoodmartJNDIDataSourceResource() => creating /analysis/datasources/FoodmartDataSourceJNDI");
        createJNDIDataSourceResource("/analysis/datasources",
                        "FoodmartDataSourceJNDI",
                        "Foodmart Data Source JNDI",
                        "Foodmart Data Source JNDI",
                        "jdbc/foodmart");
    }

    protected void createSugarCRMDataSourceResource() throws Exception {
        m_logger.info("createSugarCRMDataSourceResource() => creating /analysis/datasources/SugarCRMDataSource");

		String passwd = getJdbcProps().getProperty("test.jdbc.password");
		if (EncryptionEngine.isEncrypted(passwd)) {
			KeystoreManager ksManager = KeystoreManager.getInstance();
			passwd = EncryptionEngine.decrypt(ksManager.getKeystore(null).getKey(BuildEnc.getConfId()), passwd);
		}
		createJDBCDataSourceResource("/analysis/datasources",
                        "SugarCRMDataSource",
                        "SugarCRM Data Source",
                        "SugarCRM Data Source",
                        getJdbcProps().getProperty("test.jdbc.driverClassName"),
                        getJdbcProps().getProperty("test.jdbc.url"),
                        getJdbcProps().getProperty("test.jdbc.username"),
                        passwd);
    }

    protected void createSugarCRMDataSourceResourceJNDI() {
        m_logger.info("createSugarCRMDataSourceResourceJNDI() => creating /analysis/datasources/SugarCRMDataSourceJNDI");
        createJNDIDataSourceResource("/analysis/datasources",
                        "SugarCRMDataSourceJNDI",
                        "SugarCRM Data Source JNDI",
                        "SugarCRM Data Source JNDI",
                        "jdbc/sugarcrm");
    }

    protected void createSugarFoodmartDataSourceResourceVirtual() {
        m_logger.info("createSugarCRMDataSourceResourceVirtual() => creating /datasources/SugarFoodmartVDS");
        Map<String, String> dataSourceUriMap = new HashMap<String, String>();
        dataSourceUriMap.put("FoodmartDataSource", "FoodmartDataSourceJNDI");
        dataSourceUriMap.put("SugarCRMDataSource", "SugarCRMDataSourceJNDI");
        createVirtualDataSourceResource("/datasources",
                "/analysis/datasources",
                "SugarFoodmartVDS",
                "SugarCRM-Foodmart Virtual Data Source",
                "Virtual Data Source Combining SugarCRM and Foodmart",
                dataSourceUriMap);
    }

    public void createVirtualDataSourceResource(String dataSourceFolderParentURI,
                String subDataSourceFolderParentURI,
                String dataSourceName,
                String dataSourceLabel,
                String dataSourceDescription,
                Map<String, String> dataSourceIDMap) {
        VirtualReportDataSource dataSourceResource = (VirtualReportDataSource) getRepositoryService().getResource(null, dataSourceFolderParentURI + Folder.SEPARATOR + dataSourceName, VirtualReportDataSource.class);
        if (dataSourceResource == null) {
            dataSourceResource = (VirtualReportDataSource) getRepositoryService().newResource( null, VirtualReportDataSource.class );
            dataSourceResource.setParentFolder(dataSourceFolderParentURI);
            dataSourceResource.setName( dataSourceName );
        }
        dataSourceResource.setLabel( dataSourceLabel );
        dataSourceResource.setDescription( dataSourceDescription );
        Map<String, ResourceReference> dataSourceUriMap = new LinkedHashMap<String, ResourceReference>();

        for (Map.Entry<String, String> entry : dataSourceIDMap.entrySet()) {
            String subDataSourceUri = subDataSourceFolderParentURI + Folder.SEPARATOR + entry.getValue();
            dataSourceUriMap.put(entry.getKey(), new ResourceReference(subDataSourceUri));
        }
        dataSourceResource.setDataSourceUriMap(dataSourceUriMap);
        getRepositoryService().saveResource(null, dataSourceResource);

    }

    protected void createFoodmartJaDataSourceResource() throws Exception {
        m_logger.info("createFoodmartJaDataSourceResource() => creating /analysis/datasources/FoodmartJaDataSource");

		String passwd = getJdbcProps().getProperty("foodmart_ja.jdbc.password");
		if (EncryptionEngine.isEncrypted(passwd)) {
			KeystoreManager ksManager = KeystoreManager.getInstance();
			passwd = EncryptionEngine.decrypt(ksManager.getKeystore(null).getKey(BuildEnc.getConfId()), passwd);
		}
		createJDBCDataSourceResource("/analysis/datasources",
					"FoodmartJaDataSource",
					"Foodmart Japanese Data Source",
					"Foodmart Japanese Data Source",
					getJdbcProps().getProperty("foodmart_ja.jdbc.driverClassName"),
					getJdbcProps().getProperty("foodmart_ja.jdbc.url"),
					getJdbcProps().getProperty("foodmart_ja.jdbc.username"),
					passwd);
    }

    // move this to configuration file if people want to use
    // this for testing on a regular basis...
    private final boolean DO_PSEUDO_JAPANESE_FOODMART = false;

    public void addAnalysisResources() throws Exception {
        m_logger.info("addAnalysisResources() called");

        createFoodmartJDBCDataSourceResource();
        createFoodmartJNDIDataSourceResource();

        createSugarCRMDataSourceResource();
        createSugarCRMDataSourceResourceJNDI();

        // create virtual data source
        createSugarFoodmartDataSourceResourceVirtual();

        if (DO_PSEUDO_JAPANESE_FOODMART) {
            createFoodmartJaDataSourceResource();
        }

	    Folder analysisReports = createAnalysisReportsFolder();
        createEmployeeAccounts(analysisReports);
        createEmployees(analysisReports);
    }


    private void createEmployees(Folder folder) {
        m_logger.info("createEmployees() => creating /analysis/reports/Employees");

        FileResource reportRes = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        reportRes.setFileType(FileResource.TYPE_JRXML);
        setCommon(reportRes, "EmployeesJRXML");

        InputStream jrxml = getClass().getResourceAsStream("/reports/jasper/Employees.jrxml");
        reportRes.readData(jrxml);

        ReportUnit unit = (ReportUnit) getUnsecureRepositoryService().newResource(null, ReportUnit.class);
        unit.setName("Employees");
        unit.setLabel("Employee List");
        unit.setDescription("Employee List");
        unit.setParentFolder(folder);

        unit.setDataSourceReference("/datasources/JServerJNDIDS");
        unit.setMainReport(reportRes);

        getUnsecureRepositoryService().saveResource(null, unit);
    }

    private void createEmployeeAccounts(Folder folder) {
        m_logger.info("createEmployeeAccounts() => creating /analysis/reports/EmployeeAccounts");

        FileResource reportRes = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        reportRes.setFileType(FileResource.TYPE_JRXML);
        setCommon(reportRes, "EmployeeAccountsJRXML");

        InputStream jrxml = getClass().getResourceAsStream("/reports/jasper/EmployeeAccounts.jrxml");
        reportRes.readData(jrxml);

        ReportUnit unit = (ReportUnit) getUnsecureRepositoryService().newResource(null, ReportUnit.class);
        unit.setName("EmployeeAccounts");
        unit.setLabel("Employee Accounts");
        unit.setDescription("List of Accounts per Employee");
        unit.setParentFolder(folder);

        unit.setDataSourceReference("/datasources/JServerJNDIDS");
        unit.setMainReport(reportRes);

        InputControl empIC = (InputControl) getUnsecureRepositoryService().newResource(null, InputControl.class);
        empIC.setName("EmployeeID");
        empIC.setLabel("Employee");
        empIC.setMandatory(true);

        Query empQuery = (Query) getUnsecureRepositoryService().newResource(null, Query.class);
        empQuery.setName("EmployeeQuery");
        empQuery.setLabel("Employee Query");
        empQuery.setLanguage("sql");
        empQuery.setSql("SELECT id, user_name FROM users WHERE employee_status = 'Active'");

        empIC.setInputControlType(InputControl.TYPE_SINGLE_SELECT_QUERY);
        empIC.setQuery(empQuery);
        empIC.setQueryValueColumn("id");
        empIC.addQueryVisibleColumn("user_name");

        unit.addInputControl(empIC);
        unit.setAlwaysPromptControls(false);

        getUnsecureRepositoryService().saveResource(null, unit);
    }

    protected Folder createAnalysisReportsFolder() {
        return createOrUpdateFolder("/analysis", "reports", "Analysis Reports");
    }

    public Folder createOrUpdateFolder(String folderParentURI, String folderName, String folderLabel) {
       	Folder aFolder = null;
        ExecutionContext executionContext = StaticExecutionContextProvider.getExecutionContext();

        aFolder = getRepositoryService().getFolder(null, folderParentURI + Folder.SEPARATOR + folderName);

        if (aFolder == null) {
            aFolder = new FolderImpl();
            aFolder.setParentFolder(folderParentURI);
            aFolder.setName(folderName);
        }
    	aFolder.setLabel(folderLabel);
    	getRepositoryService().saveFolder(executionContext, aFolder);
        return aFolder;
    }

    public void createJDBCDataSourceResource(String dataSourceFolderParentURI,
                String dataSourceName,
                String dataSourceLabel,
                String dataSourceDescription,
                String driverClassName,
                String connectionURL,
                String username,
                String password) {
        JdbcReportDataSource dataSourceResource = (JdbcReportDataSource) getRepositoryService().getResource(null, dataSourceFolderParentURI + Folder.SEPARATOR + dataSourceName, JdbcReportDataSource.class);
        if (dataSourceResource == null) {
            dataSourceResource = (JdbcReportDataSource) getRepositoryService().newResource( null, JdbcReportDataSource.class );
            dataSourceResource.setParentFolder(dataSourceFolderParentURI);
            dataSourceResource.setName( dataSourceName );
        }
        dataSourceResource.setLabel( dataSourceLabel );
        dataSourceResource.setDescription( dataSourceDescription );
        dataSourceResource.setDriverClass(driverClassName);
        dataSourceResource.setConnectionUrl(connectionURL);
        dataSourceResource.setUsername(username);
        dataSourceResource.setPassword(password);
        getUnsecureRepositoryService().saveResource( null, dataSourceResource );
    }

    public void createJNDIDataSourceResource(String dataSourceFolderParentURI,
                String dataSourceName,
                String dataSourceLabel,
                String dataSourceDescription,
                String jndiURI) {
        JndiJdbcReportDataSource dataSourceResource = (JndiJdbcReportDataSource) getRepositoryService().getResource(null, dataSourceFolderParentURI + Folder.SEPARATOR + dataSourceName, JndiJdbcReportDataSource.class);
        if (dataSourceResource == null) {
            dataSourceResource = (JndiJdbcReportDataSource) getRepositoryService().newResource( null, JndiJdbcReportDataSource.class );
            dataSourceResource.setParentFolder(dataSourceFolderParentURI);
            dataSourceResource.setName( dataSourceName );
        }
        dataSourceResource.setLabel( dataSourceLabel );
        dataSourceResource.setDescription( dataSourceDescription );
        dataSourceResource.setJndiName(jndiURI);
        getUnsecureRepositoryService().saveResource( null, dataSourceResource );
    }

    private void addInteractiveReportResources()  {
        m_logger.info("addInteractiveReportResources() called");

        // create the reports folder
        m_logger.info("addInteractiveReportResources() => creating /reports");
        Folder reportsFolder = new FolderImpl();
        reportsFolder.setName("reports");
        reportsFolder.setLabel("Reports");
        reportsFolder.setDescription("Reports");
        getUnsecureRepositoryService().saveFolder(null, reportsFolder);

        // bug #22094. ROLE_USER should have write access to the /reports folder.
        Role userRole = getRole(ROLE_USER);
        createObjectPermission("/reports", userRole, JasperServerPermission.READ_WRITE_CREATE_DELETE.getMask());

        // create the interactive folder
        m_logger.info("addInteractiveReportResources() => creating /reports/interactive");
        Folder interactiveFolder = new FolderImpl();
        interactiveFolder.setName("interactive");
        interactiveFolder.setLabel("Interactive");
        interactiveFolder.setDescription("Interactive");
        interactiveFolder.setParentFolder(reportsFolder);
        getUnsecureRepositoryService().saveFolder(null, interactiveFolder);

        // create various sample reports
        createCustomersReport(interactiveFolder);
        createCustomersData(interactiveFolder);
        createCustomersDataAdapter(interactiveFolder);

        createTableReport(interactiveFolder);
        createCsvData(interactiveFolder);
        createCsvDataAdapter(interactiveFolder);

        createMapReport(interactiveFolder);
    }

    private void createCustomersReport(Folder folder) {
        m_logger.info("createCustomersReport() => creating /reports/interactive/CustomersReport");

        FileResource reportRes = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        reportRes.setFileType(FileResource.TYPE_JRXML);
        reportRes.setName("CustomersReport");
        reportRes.setLabel("Customers Report");
        reportRes.setDescription("Customers Report");
        reportRes.setParentFolder(folder);

        InputStream jrxml = getClass().getResourceAsStream("/reports/jasper/CustomersReport.jrxml");
        reportRes.readData(jrxml);

        ReportUnit unit = (ReportUnit) getUnsecureRepositoryService().newResource(null, ReportUnit.class);
        unit.setName("CustomersReport");
        unit.setLabel("Customers Report");
        unit.setDescription("Customers Report");
        unit.setParentFolder(folder);

        //unit.setDataSourceReference("/datasources/JServerJNDIDS");
        unit.setMainReport(reportRes);

        FileResource res2 = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        res2.setFileType(FileResource.TYPE_JRXML);
        res2.readData(getClass().getResourceAsStream("/reports/jasper/OrdersReport.jrxml"));
        res2.setName("OrdersReport");
        res2.setLabel("OrdersReport");
        res2.setDescription("OrdersReport");
        unit.addResource(res2);

        getUnsecureRepositoryService().saveResource(null, unit);
    }

    private void createCustomersData(Folder folder) {
        m_logger.info("createCustomersData() => creating /reports/interactive/CustomersData");

        FileResource xmlData = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        xmlData.setFileType(FileResource.TYPE_XML);
        xmlData.readData(getClass().getResourceAsStream("/reports/jasper/CustomersData.xml"));
        xmlData.setName("CustomersData");
        xmlData.setLabel("Customers Data");
        xmlData.setDescription("Customers Data");
        xmlData.setParentFolder(folder);

        getUnsecureRepositoryService().saveResource(null, xmlData);
    }

    private void createCustomersDataAdapter(Folder folder) {
        m_logger.info("createCustomersDataAdapter() => creating /reports/interactive/CustomersDataAdapter");

        FileResource xmlRes = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        xmlRes.setFileType(FileResource.TYPE_XML);
        xmlRes.readData(getClass().getResourceAsStream("/reports/jasper/CustomersDataAdapter.xml"));
        xmlRes.setName("CustomersDataAdapter");
        xmlRes.setLabel("Customers Data Adapter");
        xmlRes.setDescription("Customers Data Adapter");
        xmlRes.setParentFolder(folder);

        getUnsecureRepositoryService().saveResource(null, xmlRes);
    }

    private void createTableReport(Folder folder) {
        m_logger.info("createTableReport() => creating /reports/interactive/TableReport");

        FileResource reportRes = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        reportRes.setFileType(FileResource.TYPE_JRXML);
        reportRes.setName("TableReport");
        reportRes.setLabel("Table Report");
        reportRes.setDescription("Table Report");
        reportRes.setParentFolder(folder);

        InputStream jrxml = getClass().getResourceAsStream("/reports/jasper/TableReport.jrxml");
        reportRes.readData(jrxml);

        ReportUnit unit = (ReportUnit) getUnsecureRepositoryService().newResource(null, ReportUnit.class);
        unit.setName("TableReport");
        unit.setLabel("Table Report");
        unit.setDescription("Table Report");
        unit.setParentFolder(folder);

        //unit.setDataSourceReference("/datasources/JServerJNDIDS");
        unit.setMainReport(reportRes);

        getUnsecureRepositoryService().saveResource(null, unit);
    }

    private void createCsvData(Folder folder) {
        m_logger.info("createCsvData() => creating /reports/interactive/CsvData");

        //FileResource csvData = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        //csvData.setFileType(FileResource.TYPE_XML);
        ContentResource csvData = (ContentResource)  getUnsecureRepositoryService().newResource(null, ContentResource.class);
        csvData.setFileType(ContentResource.TYPE_CSV);
        csvData.readData(getClass().getResourceAsStream("/reports/jasper/CsvData.csv"));
        csvData.setName("CsvData");
        csvData.setLabel("CSV Data");
        csvData.setDescription("CSV Data");
        csvData.setParentFolder(folder);

        getUnsecureRepositoryService().saveResource(null, csvData);
    }

    private void createCsvDataAdapter(Folder folder) {
        m_logger.info("createCsvDataAdapter() => creating /reports/interactive/CsvDataAdapter");

        FileResource xmlRes = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        xmlRes.setFileType(FileResource.TYPE_XML);
        xmlRes.readData(getClass().getResourceAsStream("/reports/jasper/CsvDataAdapter.xml"));
        xmlRes.setName("CsvDataAdapter");
        xmlRes.setLabel("CSV Data Adapter");
        xmlRes.setDescription("CSV Data Adapter");
        xmlRes.setParentFolder(folder);

        getUnsecureRepositoryService().saveResource(null, xmlRes);
    }

    private void createMapReport(Folder folder) {
        m_logger.info("createMapReport() => creating /reports/interactive/MapReport");

        FileResource reportRes = (FileResource) getUnsecureRepositoryService().newResource(null, FileResource.class);
        reportRes.setFileType(FileResource.TYPE_JRXML);
        reportRes.setName("MapReport");
        reportRes.setLabel("Map Report");
        reportRes.setDescription("Map Report");
        reportRes.setParentFolder(folder);

        InputStream jrxml = getClass().getResourceAsStream("/reports/jasper/MapReport.jrxml");
        reportRes.readData(jrxml);

        ReportUnit unit = (ReportUnit) getUnsecureRepositoryService().newResource(null, ReportUnit.class);
        unit.setName("MapReport");
        unit.setLabel("Map Report");
        unit.setDescription("Map Report");
        unit.setParentFolder(folder);

        //unit.setDataSourceReference("/datasources/JServerJNDIDS");
        unit.setMainReport(reportRes);

        getUnsecureRepositoryService().saveResource(null, unit);
    }

}
