#
# Copyright (C) 2025 the Jasper Server OS Authors
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2005-2023. Cloud Software Group, Inc. All Rights Reserved.
# http://www.jaspersoft.com.
#
# Unless you have purchased a commercial license agreement from Jaspersoft,
# the following license terms apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

overrideDatabaseInstallTargets = true

js.drop = drop user ${js.dbName} cascade

js.create = create user ${js.dbName} identified by "${decrypt:dbPassword}"
js.privileges = grant connect, resource, unlimited tablespace to ${js.dbName}

js.set-users-password-expire = update jiuser set previouspasswordchangetime = to_date('1970-01-01', 'YYYY-MM-DD')
js.disable-users = update jiuser set enabled = false where username != 'superuser'

js.it.create = create user ${js.it.dbName} identified by "${decrypt:dbPassword}"
js.it.rest.create = create user ${js.it.rest.dbName} identified by "${decrypt:dbPassword}"
js.it.drop = drop user ${js.it.dbName} cascade
js.it.rest.drop = drop database user ${js.it.rest.dbName} cascade

foodmart.create = create user ${foodmart.dbName} identified by "${decrypt:dbPassword}"
foodmart.privileges = grant connect, resource, unlimited tablespace to ${foodmart.dbName}
foodmart.drop = drop user ${foodmart.dbName} cascade

sugarcrm.create = create user ${sugarcrm.dbName} identified by "${decrypt:dbPassword}"
sugarcrm.privileges = grant connect, resource, unlimited tablespace to ${sugarcrm.dbName}
sugarcrm.drop = drop user ${sugarcrm.dbName} cascade